---
AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Serverless Chat App
Globals:
  Function:
    Timeout: 3
  Api:
    EndpointConfiguration: EDGE
    Cors:
      AllowMethods: "'DELETE,GET,HEAD,OPTIONS,PATCH,POST,PUT'"
      AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
      AllowOrigin: "'*'"
Resources:
  ChatAPIFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: chat-api/
      Handler: index.handler
      Runtime: nodejs8.10
      Policies: AmazonS3ReadOnlyAccess
      Events:
        ProxyApiGreedy:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
Outputs:
  ChatAPIEndpoint:
    Description: API Gateway endpoint URL for Prod stage for Chat API function
    Value: !Sub https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/conversations/
  ChatAPIFunction:
    Description: Lambda Function ARN
    Value: !GetAtt ChatAPIFunction.Arn
  ChatAPIFunctionIamRole:
    Description: Implicit IAM Role created for function
    Value: !GetAtt ChatAPIFunctionRole.Arn
